### PR TITLE
Hotfix/unity5

### PR DESCRIPTION
**Pull request by nah0y**
Hello!

Just some small compilation errors fixed when using Unity5. You can merge them directly in your project if you want, it will also work on Unity 4.6 of course :)

Also, I didn't send a pull request for this because it mess up with the file diffs for one simple thing, but there are multiple classes that do not have the namespace MaterialUI, and it's causing compilation error on Unity5 too:
- MaterialUIEditorTools
- SnapButtonToTextEditor
- ColorCopier
- HSBColor
- MaterialUIScaler
- RectTransformSnap
- SnapButtonToText

Thanks for this awesome project!

### CODE REVIEW

**Comment by InvexGames** [comment]
Hey nah0y!

Thanks for the Unity 5 fixes - I'll merge those changes now and get to work with the namespacing, so it's all in the next release.

**Comment by play123** [comment]
Hi,

Great News.

Best Wishes,
play_edy

**Comment by InvexGames** [comment]
Above changes/issues are merged/fixed. Check out the latest (v0.2.3) release!

**Comment by nah0y** [comment]
Nice!
Glad I could help :)
